baseURL = "https://hugo-theme-shell.netlify.app/"
languageCode = "en-us"
title = "Het's Terminal"
theme = "hugo-theme-shell"

[Params]
    description = "Het's Portfolio"
    [Params.Terminal]
    schema = "ubuntu"
    userName = "Het-Modha"
    pcName = "linux-pc"
    workDir = "mydir"
    profile = "profile.txt"

    description = """
    Hi I am Het Modha! Welcome to my terminal portfolio.
    It includes my GitHub, LinkedIn, personal website and twitter handle.
    Do follow me on these platforms.
    Hope you like your stay, it was nice meeting you!
    """
    [Params.Tree]
    use = true
    files = [
        ["GitHub", "https://github.com/hdmodha"],
        ["LinkedIn", "https://www.linkedin.com/in/hdmodha15/"],
        ["CV", "https://hdmodha.github.io/cv"],
        ["Website", "https://hdmodha.github.io/portfolio/"],
        ["Twitter", "https://twitter.com/HdModha"]    
    ]
