baseURL = "https://hugo-theme-shell.netlify.app/"
languageCode = "en-us"
title = "Het's Terminal"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "ubuntu"
    userName = "Het-Modha"
    pcName = "linux-pc"
    workDir = "mydir"
    profile = "profile.txt"

    description = """
    Hi I am Het Modha! Welcome to my terminal portfolio.
    """
    [Params.Tree]
    use = true
    files = [
        ["C/C++", "https://www.example.com/"],
        ["Python", "https://www.example.com/"],
        ["Go", "/works/go.md"],
        ["Hugo", "/works/hugo.md"]
    ]
